# Basic Python

## 1. Split this string

In [13]:
s = "Hi there Sam!"

In [14]:
s = "Hi there Sam!"
a = s.split()
print (a)

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [15]:
planet = "Earth"
diameter = 12742

In [16]:
planet = "Earth"
diameter = 12742
text = "The diameter of {planet} is {diameter} kilometers."
print(text.format(planet = "Earth",diameter = 12742))

The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [17]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [18]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
a='hello'
for a in d:
    print('hello')


hello


# Numpy

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [20]:
import numpy as np
array=np.zeros(10)
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [21]:
import numpy as np
array=np.ones(10)*5
print(array)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [26]:
import numpy as np
array=np.arange(20,35,2)

print(array)

[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [27]:
import numpy as np
arr = np.arange(0,9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [28]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
array = np.concatenate((a, b))
print(array)

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [32]:
import pandas as pd
data = [['sara', 10], ['carlo', 15], ['victor', 14]]
df = pd.DataFrame(data, columns=['Name', 'Age'])
df

Name  Age
0    sara   10
1   carlo   15
2  victor   14

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [23]:
import pandas
d = pandas.date_range(start='1/1/2023', end='10/2/2023')    
print(d)

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10',
               ...
               '2023-09-23', '2023-09-24', '2023-09-25', '2023-09-26',
               '2023-09-27', '2023-09-28', '2023-09-29', '2023-09-30',
               '2023-10-01', '2023-10-02'],
              dtype='datetime64[ns]', length=275, freq='D')


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [24]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [25]:
import pandas as pd 
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]    
df = pd.DataFrame(lists, columns =['No', 'Name','age']) 
print(df )

   No Name  age
0   1  aaa   22
1   2  bbb   25
2   3  ccc   24
